### PR TITLE
add "auto" protocol

### PR DESCRIPTION
**Pull request by myshzzx**
Now one can subscribe a page without rss/atom offered.

for example, one would like to subscribe page `https://medium.com/topic/artificial-intelligence`, 
add a feed like `autohttps://medium.com/topic/artificial-intelligence@h1 a,h3 a@div.section-inner
`, this means collecting news from the page using css selector `h1 a,h3 a`, the `a` text as news' title and link as news' link, the news target page as news' content (by default), here `div.section-inner` means select news content by css selector `div.section-inner` from news page (optional).

`autohttp[s]://url.xxx/@[item-selector]@[item-target-page-content-selector(optional)]`

### CODE REVIEW

**Comment by Xyrio** [comment]
i prefer solutions that generate a rss/atom. thats much easier to maintain. something like `https://fetchrss.com` but as an embedded webserver into rssowl. the website for making such an rss is separate from the the part that processes the special url.

**Comment by myshzzx** [comment]
in my view, rss/atom is fading away from common live, many valuable info sources don't provide rss/atom, but distributing information via their own apps instead, so there's no need to adapt rss/atom.
the value of rssowl is providing a way to manage information, rss/atom is just an information digest that calling people "subscribe me, subscribe me".

when I subscribe a source, I care about the title and the content, the most easy way to create an url describing what I want without a GUI-CSS-selector generator, is a fixed position scheme, and seems nothing to extend in a few years. one day you got a more easy way to create such an url like `collect://auto?url=xxx&title=[selector]&author=[selector]&content=[selector]...` by some mouse click, you can simply adapt `autohttp` to `collect`. in fact `autohttp` scheme is offered to programmer, since css-selector is hard for common user.

**Comment by Xyrio** [comment]
since 2.8.0 one can use shell:// protocol to call external scripts that provide the rss content.

**Comment by myshzzx** [comment]
now I use chrome extension feedbro:
https://chrome.google.com/webstore/detail/feedbro/mefgmmbdailogpfhfblcnnjfmnpnmdfa

as to generate atom content, I build one myself, which can parse any page like 

http://localhost:55555/genAtom?info=http%3A%2F%2Fwww.zhuanzhi.ai%2F%40div._type_serif_title_medium%20a%40%23page-content

image

**Comment by Xyrio** [comment]
the easies way to create the special url i have encountered is https://fetchrss.com/ (not free however)
then another way seen is to use regex instead of css selectors.

using a webserver to do the work was always possible, now you can have just a script and dont need to run some separate application. external scripts are easier to change adapt than having to rebuild rssowlnix every time. you can also use any scripting/programming language you want.

most rss aggregators are too simple for me. i dont know of any rss aggregator that can compete with rssowl, even with problems it has.

**Pull request closed without merging**
