### PR TITLE
Updated the license to 2.0

### PR DESCRIPTION
**Pull request by 4GAP3**
This license is the latest license to EPL. It added some more exceptions, and it's formatted better.

### CODE REVIEW

**Comment by Xyrio** [comment]
afaik license cannot be changed without consent of all involved...

**Comment by 4GAP3** [comment]
Ok, I will try to see what I can do in term of updating the licenses

**Comment by Xyrio** [comment]
what is the update for? seems like a waste of time.

**Comment by 4GAP3** [comment]
I'm just trying to contribute to the project is all.

**Comment by Xyrio** [comment]
well if you have fun doing it ill merge it. but it is nothing important i think.

**Pull request closed without merging**
